### ISSUE TITLE
Trying to get this worked with latest versions of buf

### ISSUE THREAD

**Issue by devansh-dalal** [Wizhi/setup-buf#6]
With the `.github/workflows/buf_checks.yaml`
```
name: Proto Backward compatibility checks on pull requests

on: pull_request

jobs:

  breaking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: Spotnana-Tech/setup-buf@v1
        with:
          version: 0.43.0
      - run: buf breaking --against ".git#branch=${{ github.base_ref }}" --against-config src/infra/ci-cd/build/tools/buf/buf.yaml --config src/infra/ci-cd/build/tools/buf/buf.yaml --verbose
```

and `buf.yaml` as
```
# For breaking, recommendation is having the single value "FILE" in use.
# See https://docs.buf.build/lint-usage
# See https://docs.buf.build/breaking-usage
version: v1beta1
build:
  roots:
    - src/java/protos/src/main/proto
breaking:
  use:
    - FILE
~              
```

we are getting this error in git action,
<img width="1357" alt="Screenshot 2021-07-12 at 8 30 04 AM" src="https://user-images.githubusercontent.com/69784585/125224923-0a6ce500-e2ec-11eb-8984-5fbf506758a6.png">

Everything runs smoothly on local. 
Would be very helpful if some can give insights to whats is missing
